In [1]:
import pandas as pd
from pandas import json_normalize
import json

In [2]:
# loading JSON file
with open("flights.json", "r", encoding="utf-8") as f:
    all_flights = json.load(f)

# list?
assert isinstance(all_flights, list)

In [9]:
all_flights_df = json_normalize(all_flights)

In [10]:
all_flights_df.isna().sum()

flight_date                           0
flight_status                         0
aircraft                           1200
live                               1200
departure.airport                     0
departure.timezone                    0
departure.iata                        0
departure.icao                        0
departure.terminal                  202
departure.gate                      553
departure.delay                     449
departure.scheduled                   0
departure.estimated                   0
departure.actual                    926
departure.estimated_runway          926
departure.actual_runway             926
arrival.airport                       4
arrival.timezone                      4
arrival.iata                          0
arrival.icao                          0
arrival.terminal                    587
arrival.gate                        956
arrival.baggage                     842
arrival.scheduled                     0
arrival.delay                      1118
arrival.estimated                  1200
arrival.actual                     1192
arrival.estimated_runway           1192
arrival.actual_runway              1192
airline.name                          2
airline.iata                          0
airline.icao                          0
flight.number                        22
flight.iata                           0
flight.icao                           0
flight.codeshared.airline_name      565
flight.codeshared.airline_iata      565
flight.codeshared.airline_icao      565
flight.codeshared.flight_number     565
flight.codeshared.flight_iata       565
flight.codeshared.flight_icao       565
flight.codeshared                  1200
dtype: int64

In [3]:
df_departure = json_normalize(
    all_flights,
    meta=['flight_date', 'flight_status'],
    record_prefix='departure.'
)[[
    'departure.airport',
    'departure.timezone',
    'departure.iata',
    'departure.icao',
    'departure.terminal',
    'departure.gate',
    'departure.delay',
    'departure.scheduled',
    'departure.estimated',
    'departure.actual',
    'departure.estimated_runway',
    'departure.actual_runway'
]]

In [4]:
df_departure

,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,departure.delay,departure.scheduled,departure.estimated,departure.actual,departure.estimated_runway,departure.actual_runway
0,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
1,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
2,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
3,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
4,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Charles De Gaulle,Europe/Paris,CDG,LFPG,2F,F05,17.0,2025-07-31T07:05:00+00:00,2025-07-31T07:05:00+00:00,None,None,None
1196,Charles De Gaulle,Europe/Paris,CDG,LFPG,2F,F05,17.0,2025-07-31T07:05:00+00:00,2025-07-31T07:05:00+00:00,None,None,None
1197,Charles De Gaulle,Europe/Paris,CDG,LFPG,2F,F05,17.0,2025-07-31T07:05:00+00:00,2025-07-31T07:05:00+00:00,None,None,None
1198,Charles De Gaulle,Europe/Paris,CDG,LFPG,2F,F05,18.0,2025-07-31T07:05:00+00:00,2025-07-31T07:05:00+00:00,None,None,None
1199,Charles De Gaulle,Europe/Paris,CDG,LFPG,2F,F05,18.0,2025-07-31T07:05:00+00:00,2025-07-31T07:05:00+00:00,None,None,None

In [31]:
df_departure.duplicated().sum()

np.int64(1013)

In [33]:
df_departure.head()

,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,departure.delay,departure.scheduled,departure.estimated,departure.actual,departure.estimated_runway,departure.actual_runway
0,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
1,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
2,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
3,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
4,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None

In [34]:
df_departure.drop_duplicates(inplace=True)

In [36]:
df_departure

,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,departure.delay,departure.scheduled,departure.estimated,departure.actual,departure.estimated_runway,departure.actual_runway
0,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
6,Heathrow,Europe/London,LHR,EGLL,5,B38,11.0,2025-07-30T07:50:00+00:00,2025-07-30T07:50:00+00:00,None,None,None
10,Heathrow,Europe/London,LHR,EGLL,2,A18,12.0,2025-07-30T08:00:00+00:00,2025-07-30T08:00:00+00:00,2025-07-30T08:11:00+00:00,2025-07-30T08:11:00+00:00,2025-07-30T08:11:00+00:00
13,Heathrow,Europe/London,LHR,EGLL,3,29,11.0,2025-07-30T07:20:00+00:00,2025-07-30T07:20:00+00:00,2025-07-30T07:31:00+00:00,2025-07-30T07:31:00+00:00,2025-07-30T07:31:00+00:00
14,Heathrow,Europe/London,LHR,EGLL,5,A6,20.0,2025-07-30T09:15:00+00:00,2025-07-30T09:15:00+00:00,2025-07-30T09:34:00+00:00,2025-07-30T09:34:00+00:00,2025-07-30T09:34:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
705,Charles De Gaulle,Europe/Paris,CDG,LFPG,2F,F53,7.0,2025-07-31T08:25:00+00:00,2025-07-31T08:25:00+00:00,None,None,None
706,Charles De Gaulle,Europe/Paris,CDG,LFPG,2E,M28,13.0,2025-07-31T08:25:00+00:00,2025-07-31T08:25:00+00:00,None,None,None
709,Charles De Gaulle,Europe/Paris,CDG,LFPG,2E,L53,10.0,2025-07-31T08:30:00+00:00,2025-07-31T08:30:00+00:00,None,None,None
800,Heathrow,Europe/London,LHR,EGLL,4,20,16.0,2025-07-31T08:55:00+00:00,2025-07-31T08:55:00+00:00,None,None,None
801,Heathrow,Europe/London,LHR,EGLL,5,10B,NaN,2025-07-31T08:55:00+00:00,2025-07-31T08:55:00+00:00,None,None,None

In [7]:
df_lhr_departure = df_departure[df_departure["departure.iata"] == "LHR"]    
df_cgd_departure = df_departure[df_departure["departure.iata"] == "CGD"]

In [40]:
df_lhr_departure

,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,departure.delay,departure.scheduled,departure.estimated,departure.actual,departure.estimated_runway,departure.actual_runway
0,Heathrow,Europe/London,LHR,EGLL,2,A17,NaN,2025-07-30T06:00:00+00:00,2025-07-30T06:00:00+00:00,None,None,None
6,Heathrow,Europe/London,LHR,EGLL,5,B38,11.0,2025-07-30T07:50:00+00:00,2025-07-30T07:50:00+00:00,None,None,None
10,Heathrow,Europe/London,LHR,EGLL,2,A18,12.0,2025-07-30T08:00:00+00:00,2025-07-30T08:00:00+00:00,2025-07-30T08:11:00+00:00,2025-07-30T08:11:00+00:00,2025-07-30T08:11:00+00:00
13,Heathrow,Europe/London,LHR,EGLL,3,29,11.0,2025-07-30T07:20:00+00:00,2025-07-30T07:20:00+00:00,2025-07-30T07:31:00+00:00,2025-07-30T07:31:00+00:00,2025-07-30T07:31:00+00:00
14,Heathrow,Europe/London,LHR,EGLL,5,A6,20.0,2025-07-30T09:15:00+00:00,2025-07-30T09:15:00+00:00,2025-07-30T09:34:00+00:00,2025-07-30T09:34:00+00:00,2025-07-30T09:34:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
491,Heathrow,Europe/London,LHR,EGLL,2,C,NaN,2025-07-31T07:05:00+00:00,2025-07-31T07:05:00+00:00,None,None,None
494,Heathrow,Europe/London,LHR,EGLL,3,E,NaN,2025-07-31T07:10:00+00:00,2025-07-31T07:10:00+00:00,None,None,None
497,Heathrow,Europe/London,LHR,EGLL,5,None,NaN,2025-07-31T07:10:00+00:00,2025-07-31T07:10:00+00:00,None,None,None
800,Heathrow,Europe/London,LHR,EGLL,4,20,16.0,2025-07-31T08:55:00+00:00,2025-07-31T08:55:00+00:00,None,None,None
801,Heathrow,Europe/London,LHR,EGLL,5,10B,NaN,2025-07-31T08:55:00+00:00,2025-07-31T08:55:00+00:00,None,None,None

In [8]:
df_lhr_departure["departure.scheduled"].min(), df_departure["departure.scheduled"].max()

('2025-07-30T06:00:00+00:00', '2025-07-31T09:15:00+00:00')